### ISSUE TITLE
fill sample_genotype_counts table

### ISSUE THREAD

**Issue by davemcg** [quinlan-lab/vcf2db#19]
```
gemini stats --gts-by-sample CCGO.2016-12-09.db
```

```
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
sample  num_hom_ref     num_het num_hom_alt     num_unknown     total
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 573, in stats_fn
    gemini_stats.stats(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_stats.py", line 299, in stats
    get_gtcounts_by_sample(conn, metadata, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_stats.py", line 250, in get_gtcounts_by_sample
    res = conn.execute(query)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1034, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: sample_genotype_counts [SQL: u'SELECT *,              (num_hom_ref + num_het + num_hom_alt + num_unknown) as total              FROM sample_genotype_counts']
```

I find this useful to get a rough overview of variants called for each sample. Occasionally a weird samples gets through QC which has too many or too few variants.

**Comment by brentp** [comment]
did you load this with vcf2db?

**Comment by davemcg** [comment]
Oh, yes I did.

**Comment by brentp** [comment]
... oh, I assume so since you opened on this repo.

**Comment by brentp** [comment]
ok. that should be fairly straightforward to add. I might not get to it right away.

**Comment by davemcg** [comment]
cool, thanks

**Comment by brentp** [comment]
this is fixed in master
