### ISSUE TITLE
Just be aware that sqlite (sqlite3) does not work with AWS EFS drive.

### ISSUE THREAD

**Issue by spz1st** [quinlan-lab/vcf2db#22]
I got the following error when I tried the command "python vcf2db.py test.vcf test.ped test.db"  at an EFS drive on a cfncluster.  It produced an empty db file.  But it worked if I tried to produce the db file somewhere else, like "python vcf2db.py test.vcf test.ped ~/test.db".

<blockquote>
Traceback (most recent call last):
  File "vcf2db.py", line 806, in <module>
    VCFDB(a.VCF, a.db, a.ped, black_list=a.info_exclude, expand=a.expand, blobber=main_blo
bber)
  File "vcf2db.py", line 213, in __init__
    self.samples = self.create_samples()
  File "vcf2db.py", line 534, in create_samples
    t.create()
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/sql/sch
ema.py", line 742, in create
    checkfirst=checkfirst)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
base.py", line 1920, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
base.py", line 1529, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/sql/vis
itors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/sql/ddl
.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/sql/ddl
.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
base.py", line 1002, in _execute_ddl
    compiled
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
base.py", line 1189, in _execute_context
    context)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/util/co
mpat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
base.py", line 1182, in _execute_context
    context)
  File "/home/centos/miniconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/
default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error [SQL: u'\nCREAT
E TABLE samples (\n\tsample_id INTEGER NOT NULL, \n\tfamily_id VARCHAR(1), \n\tname VARCHA
R(5), \n\tpaternal_id VARCHAR(5), \n\tmaternal_id VARCHAR(5), \n\tsex VARCHAR(2), \n\tphen
otype VARCHAR(2), \n\textra VARCHAR(3), \n\tPRIMARY KEY (sample_id)\n)\n\n']
</blockquote>

**Comment by brentp** [comment]
Thanks for reporting.
closed in #23
