### ISSUE TITLE
Problem with vct to db conversion

### ISSUE THREAD

**Issue by alphahmed18** [quinlan-lab/vcf2db#39]
Hi Brent,

Thanks in advance for your kind help..

The vcf2db tool, combined with vcfanno and gemini, have been serving our lab greatly. However, I'd like to ask you please about the reason behind getting the following error script lately; when I try to convert my annotated vcf file. Am I doing anything wrong? The vcf file outputs of the same vcfanno '.conf' used to work fine with vcf2db.
-----------------------------------------------
$ python ~/gemini/vcf2db/vcf2db.py HiDP_Macro_vcfanno.vcf ../Macro_fam.ped HiDP_Macro.db
skipping 'AC' because it has Number=A
skipping 'AF' because it has Number=A
skipping 'MLEAC' because it has Number=A
skipping 'MLEAF' because it has Number=A
skipping 'ac_gnomad_afr' because it has Number=A
skipping 'ac_gnomad_all' because it has Number=A
skipping 'ac_gnomad_amr' because it has Number=A
skipping 'ac_gnomad_asj' because it has Number=A
skipping 'ac_gnomad_eas' because it has Number=A
skipping 'ac_gnomad_fin' because it has Number=A
skipping 'ac_gnomad_nfe' because it has Number=A
skipping 'ac_gnomad_oth' because it has Number=A
skipping 'num_exac_Het' because it has Number=A
skipping 'num_exac_Hom' because it has Number=A
/home/ahmed/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:219: SAWarning: Unicode type received non-unicode bind param value 'Macro'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/home/ahmed/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:219: SAWarning: Unicode type received non-unicode bind param value '2'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/home/ahmed/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:219: SAWarning: Unicode type received non-unicode bind param value '-9'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
Traceback (most recent call last):
  File "/home/ahmed/gemini/vcf2db/vcf2db.py", line 915, in <module>
    impacts_extras=a.impacts_field, aok=a.a_ok)
  File "/home/ahmed/gemini/vcf2db/vcf2db.py", line 231, in __init__
    self.load()
  File "/home/ahmed/gemini/vcf2db/vcf2db.py", line 316, in load
    i = self._load(self.cache, create=True, start=1)
  File "/home/ahmed/gemini/vcf2db/vcf2db.py", line 309, in _load
    self.insert(variants, expanded, keys, i, create=create)
  File "/home/ahmed/gemini/vcf2db/vcf2db.py", line 344, in insert
    if af_val is None or af_val == "" or (not isinstance(af_val, basestring) and np.isnan(af_val)):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[ahmed@jupiter new2]$ gemini load HiDP_Macro_vcfanno.vcf > HiDP_Macro.db
Traceback (most recent call last):
  File "/home/ahmed/gemini/tools/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1248, in main
    args.func(parser, args)
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 203, in load_fn
    args.vcf = os.path.abspath(args.vcf)
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
---------------------------------------------

Best regards,
Ahmed

**Comment by brentp** [comment]
For the vcf2db error, if you pull the latest version from github, you'll
get a message showing you which column it was.
From the error, I can tell you that it's one of the AF columns and it has
multiple values so you'll need to decompose your vcf or add that column to
the --info-exclude list.
-Brent

**Comment by alphahmed18** [comment]
Thanks a lot Brent! that was really useful. 

I found that the parameter causing the error was "pg" with values of (0,0,0), which is "nmd" on the 'variants' table output. I am using a modified vcfanno configuration file from the gemini one in vcfanno/examples repository. I tried to find out which line in the config file was responsible for it, but couldn't find it. I had to exclud it, since the only output I got, anyway, was an HLA-related annotation for one variant (all the rest of variants have "None" values).

I will keep you posted with any bugs I might find, and try to do anything possible to make your tools accessible and useful for more users.

Regards,
Ahmed
