### ISSUE TITLE
list index out of range error?

### ISSUE THREAD

**Issue by shukwong** [quinlan-lab/vcf2db#6]
Thanks for putting this together, it would be very helpful for me! 

I tried the test files but got the following error. I was wondering if it has to do with my installation?

wwong@login1:~> python /itmi/vcf2db-master/vcf2db.py /itmi/vcf2db-master/tests/test.vcf /itmi/vcf2db-master/tests/test.ped test.db
pedigree notice: '1_dad' is dad but has unknown sex. Setting to male
pedigree notice: '1_mom' is mom but has unknown sex. Setting to female
pedigree notice: '2_dad' is dad but has unknown sex. Setting to male
pedigree notice: '2_mom' is mom but has unknown sex. Setting to female
pedigree notice: '3_dad' is dad but has unknown sex. Setting to male
pedigree notice: '3_mom' is mom but has unknown sex. Setting to female

Traceback (most recent call last):
  File "/itmi/vcf2db-master/vcf2db.py", line 663, in <module>
    blobber=blobber)
  File "/itmi/vcf2db-master/vcf2db.py", line 155, in **init**
    self.load()
  File "/itmi/vcf2db-master/vcf2db.py", line 214, in load
    i = self._load(self.cache, create=True, start=1)
  File "/itmi/vcf2db-master/vcf2db.py", line 207, in _load
    self.insert(variants, expanded, keys, i, create=create)
  File "/itmi/vcf2db-master/vcf2db.py", line 234, in insert
    v in variants)
  File "/itmi/vcf2db-master/vcf2db.py", line 589, in gene_info
    top = geneimpacts.Effect.top_severity(impacts)
  File "/itmi/Python-2.7_Anaconda/lib/python2.7/site-packages/geneimpacts-0.1.1-py2.7.egg/geneimpacts/effect.py", line 300, in top_severity
    if effects[-1] > effects[-2]:
IndexError: list index out of range

**Comment by brentp** [comment]
you'll have to run: `pip install -U git+git://github.com/brentp/geneimpacts.git#egg=geneimpacts`

**Comment by brentp** [comment]
I'm going to close this, if you still have this problem please re-open and I'll be glad to help.
