### ISSUE TITLE
Cannot parse VEP Mastermind CSQ tags which contains URL

### ISSUE THREAD

**Issue by nswh** [quinlan-lab/vcf2db#67]
Whet the annotated VCF has Mastermind URL in CSQ tags, vcf2db.py throw the following error: 

Traceback (most recent call last):
  File "/opt/vcf2db/vcf2db.py", line 923, in <module>
    impacts_extras=a.impacts_field, aok=a.a_ok)
  File "/opt/vcf2db/vcf2db.py", line 233, in __init__
    self.load()
  File "/opt/vcf2db/vcf2db.py", line 318, in load
    i = self._load(self.cache, create=True, start=1)
  File "/opt/vcf2db/vcf2db.py", line 311, in _load
    self.insert(variants, expanded, keys, i, create=create)
  File "/opt/vcf2db/vcf2db.py", line 340, in insert
    v in variants)
  File "/opt/vcf2db/vcf2db.py", line 809, in gene_info
    impacts.extend(cls(e, impacts_headers[k]) for e in dk)
  File "/opt/vcf2db/vcf2db.py", line 809, in <genexpr>
    impacts.extend(cls(e, impacts_headers[k]) for e in dk)
  File "/opt/conda/lib/python2.7/site-packages/geneimpacts/effect.py", line 530, in __init__
    assert not "=" in effect_string
AssertionError

Script submitted is as below: 

vcf2db.py \
            ${VCF_IN} \
            ${PED} \
            ${DB_OUT} \
            --expand gt_types \
            --expand gt_ref_depths \
            --expand gt_alt_depths

Input files attached. 
[hg38validation_quartet.30t.vcf.gz](https://github.com/quinlan-lab/vcf2db/files/6105473/hg38validation_quartet.30t.vcf.gz)

[hg38validation_quartet.vcf.ped.txt](https://github.com/quinlan-lab/vcf2db/files/6105566/hg38validation_quartet.vcf.ped.txt)

**Comment by brentp** [comment]
Hi, unfortunately, these annotations are not supported. I'd accept a pull-request to fix this.
