### ISSUE TITLE
Issue with PED file

### ISSUE THREAD

**Issue by nvnieuwk** [quinlan-lab/vcf2db#70]
Hi, I'm trying to convert an annotated VCF to a DB file, but I'm getting the following error:
```
  skipping 'AC' because it has Number=A
  skipping 'AF' because it has Number=A
  skipping 'AS_BaseQRankSum' because it has Number=A
  skipping 'AS_FS' because it has Number=A
  skipping 'AS_InbreedingCoeff' because it has Number=A
  skipping 'AS_MQ' because it has Number=A
  skipping 'AS_MQRankSum' because it has Number=A
  skipping 'AS_QD' because it has Number=A
  skipping 'AS_ReadPosRankSum' because it has Number=A
  skipping 'AS_SOR' because it has Number=A
  skipping 'DRAGstrInfo' because it has Number=2
  skipping 'DRAGstrParams' because it has Number=3
  skipping 'MLEAC' because it has Number=A
  skipping 'MLEAF' because it has Number=A
  skipping 'RAW_GT_COUNT' because it has Number=3
  skipping 'RAW_MQandDP' because it has Number=2
  Traceback (most recent call last):
    File "/usr/local/bin/vcf2db.py", line 923, in <module>
      VCFDB(a.VCF, a.db, a.ped, black_list=a.info_exclude, expand=a.expand, blobber=main_blobber,
    File "/usr/local/bin/vcf2db.py", line 228, in __init__
      self.samples = self.create_samples()
    File "/usr/local/bin/vcf2db.py", line 568, in create_samples
      ped = Ped(self.ped_path)
    File "/usr/local/lib/python3.8/site-packages/peddy/peddy.py", line 441, in __init__
      self._parse(ped)
    File "/usr/local/lib/python3.8/site-packages/peddy/peddy.py", line 460, in _parse
      sample = Sample.from_row(toks, header=self.header, warn=self.warn)
    File "/usr/local/lib/python3.8/site-packages/peddy/peddy.py", line 262, in from_row
      return cls(row[0], row[1], row[2] or "-9", row[3] or "-9", row[4], row[5],
  IndexError: list index out of range
```

I think there is something wrong with my PED file, but I don't know what it is and it was fine for some other tools I used. My PED file is the following:

```
#PED format pedigree
#
#fam-id/ind-id/pat-id/mat-id: 0=unknown
#sex: 1=male; 2=female; 0=unknown
#phenotype: -9=missing, 0=missing; 1=unaffected; 2=affected
#
#fam-id             ind-id              pat-id  mat-id  sex     phen
Family_12345       NA12878K12_NVQ_034  NA24385D2_NVQ_034 0 2       0
Family_12345       NA24385D2_NVQ_034   0       0       1       0
```

The used command is:
```
vcf2db.py \
   Family_12345.vcf.gz \
   NA12878.ped \
   Family_12345.db
```

Is there anyone that can help me identify what is wrong and how to fix it?

**Comment by nvnieuwk** [comment]
Note: I'm using this Docker version: `quay.io/biocontainers/vcf2db:2020.02.24--hdfd78af_1`

**Comment by Bin-Guan** [comment]
You may try sed 's/Number=A/Number=1/g', if your vcf files are decomposed.

**Comment by nvnieuwk** [comment]
Thanks for your response! I'll give it a go on monday!

**Comment by brentp** [comment]
Do you have an empty line at the end of your pedigree file? Or maybe you need to remove the comments at the top. If you update peddy in yoru container, you'll probably get a better error message.

**Comment by nvnieuwk** [comment]
@brentp Thanks for your response, removing all comments except for the header worked :)
