### ISSUE TITLE
Can vcf2db be used without a PED file?

### ISSUE THREAD

**Issue by komalsrathi** [quinlan-lab/vcf2db#8]
I have a set of Exome Bam files and I created an annotated vcf using - GATK, snpEff and vcfanno. Now I want to create a gemini compatible database from the vcfanno output but I don't have a Pedigree file associated with my samples. How can I still create a gemini db?

**Comment by brentp** [comment]
You'll have to create a fake ped, something like

```
zgrep -m1 CHROM $vcf | cut -f 10- | awk 'BEGIN{RS="\t"}{ printf("fam%d\t%s\t0\t0\t-9\t-9\n", NR, $1) }' 
```

**Comment by komalsrathi** [comment]
this is my vcfanno output (removed the header):
google drive link: https://drive.google.com/open?id=0B-8gQV1WZcYdaVlzOXdrN2FzN3M

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  20
chr4    54243811        .       C       <NON_REF>       .       .       END=54243904    GT:DP:GQ:MIN_DP:PL      0/0:208:99:129:0,120,1800
chr4    54243905        .       T       C,<NON_REF>     10162.8 .       DP=280;MLEAC=2,0;MLEAF=1.00,0.00;MQ=59.94;EFF=UTR_5_PRIME(MODIFIER||101||594|FIP1L1|protein_coding|CODING|ENST00000337488|1|C),UTR_5_PRIME(MODIFIER||101||588|FIP1L1|protein_coding|CODING|ENST00000358575|1|C),UTR_5_PRIME(MODIFIER||101||378|FIP1L1|protein_coding|CODING|ENST00000507922|1|C),UTR_5_PRIME(MODIFIER||101||520|FIP1L1|protein_coding|CODING|ENST00000306932|1|C),EXON(MODIFIER|||||FIP1L1|processed_transcript|CODING|ENST00000511376|1|C);variant_type=SNP    GT:AD:DP:GQ:PL:SB       1/1:0,268,0:268:99:10191,805,0,10191,805,10191:0,0,160,108
chr4    54243906        .       C       <NON_REF>       .       .       END=54244236    GT:DP:GQ:MIN_DP:PL      0/0:170:99:37:0,99,1485
chr4    54244237        .       T       <NON_REF>       .       .       END=54244238    GT:DP:GQ:MIN_DP:PL      0/0:36:90:35:0,90,1350
```

This is how the ped file (my.ped) was created:

```
fam1    20  0   0   -9  -9
```

Command:

```
gemini_python vcf2db.py --legacy-compression my.ped sample_new.snpeff.gvcf.anno.gz my.db
```

I get the following error:

```
[E::bcf_hdr_read] invalid BCF2 magic string
Segmentation fault
```

**Comment by brentp** [comment]
Is it gzipped?

**Comment by komalsrathi** [comment]
It should be - this was my command:

```
vcfanno -p 4 -base-path /mnt/isilon/cbmi/variome/bin/gemini/data/gemini_data -lua vcfanno.lua vcfanno.conf sample_new.snpeff.gvcf | bgzip -c > sample_new.snpeff.gvcf.anno.gz
```

**Comment by brentp** [comment]
oh, the argument order is `$vcf $ped $db`
you have `$ped $vcf $db`

**Comment by komalsrathi** [comment]
Ok I changed the commandline to this:

```
gemini_python /mnt/isilon/cbmi/variome/bin/vcf2db/vcf2db.py --legacy-compression sample_new.snpeff.gvcf.anno.gz my.ped my.db
```

```
Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/vcf2db/vcf2db.py", line 720, in <module>
    blobber=blobber)
  File "/mnt/isilon/cbmi/variome/bin/vcf2db/vcf2db.py", line 175, in __init__
    self.load()
  File "/mnt/isilon/cbmi/variome/bin/vcf2db/vcf2db.py", line 237, in load
    i = self._load(self.cache, create=True, start=1)
  File "/mnt/isilon/cbmi/variome/bin/vcf2db/vcf2db.py", line 193, in _load
    must_idx = not np.all(self.sample_idxs == range(len(self.sample_idxs)))
TypeError: object of type 'NoneType' has no len()
```

Just an FYI: I have successfully been able to run the same commandline previously on a different set of samples.

**Comment by brentp** [comment]
can you attach the first few lines sample_new.snpeff.gvcf.anno.gz with the header and a few variants so I can test?

**Comment by komalsrathi** [comment]
I have the google drive link for the full file in my second comment. It is a very small vcf.

**Comment by brentp** [comment]
Got it. Thanks. I just pushed a commit that fixes. After that I was able to load your VCF successfully.

**Comment by komalsrathi** [comment]
I think I might have to add one more column for phenotype in the ped file. The awk command generates 6 columns.

**Comment by brentp** [comment]
After the latest fix, I loaded with only `fam1  20  0   0   -9  -9` in the ped file.
A ped file only requires 6 columns.

**Comment by komalsrathi** [comment]
Ok that worked but I don't know why gemini (v0.18.3) is failing when I try to query. (I have successfully used the same version of gemini before):

```
[rathik@respublica-an mutations]$ gemini_python /home/rathik/tools/vcf2db/vcf2db.py sample_new.snpeff.gvcf.anno.gz my.ped my.db

unknown sample: name in family: sample_id
unknown sample: paternal_id in family: sample_id
not in VCF: family_id
/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'fam1'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '-9'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
10000 variant_impacts:1019  effects time: 0.7   chunk time:3.0  3340.47 variants/second
20000 variant_impacts:139   effects time: 0.5   chunk time:2.4  3740.24 variants/second
30000 variant_impacts:457   effects time: 0.7   chunk time:2.5  3809.37 variants/second
33336 variant_impacts:169   effects time: 0.2   chunk time:0.8  3825.43 variants/second
indexing ... finished in 2.1 seconds...
total time: in 10.8 seconds...
```

I can successfully dump the variants and samples:

```
[rathik@respublica-an mutations]$ gemini dump --samples my.db
2   fam1    20  -9  -9  -9  -9
[rathik@respublica-an mutations]$ gemini dump --variants my.db | head
28729   chr11   61170121    61170132    .   C   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28730   chr11   61170132    61170487    .   T   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28731   chr11   61170487    61170541    .   C   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28732   chr11   61170541    61170542    .   T   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28733   chr11   61170542    61170552    .   G   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28734   chr11   61170552    61170553    .   T   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28735   chr11   61170553    61170559    .   T   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28736   chr11   61170559    61170560    .   A   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28737   chr11   61170560    61170563    .   C   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
28738   chr11   61170563    61170566    .   G   <NON_REF>   .   .   indel   ins 1.0 1   0   0   0.0 .   .   .   .   .   None    .   None    None    .   None    .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
```

But I cannot query:

```
[rathik@respublica-an mutations]$ gemini query -q "select * from variants" my.db | head

Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/gemini/tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 422, in query_fn
    gemini_query.query(parser, args)
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_query.py", line 165, in query
    run_query(args)
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_query.py", line 121, in run_query
    subjects = get_subjects(args)
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_subjects.py", line 138, in get_subjects
    gq = GeminiQuery.GeminiQuery(args.db)
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 546, in __init__
    self.idx_to_sample = util.map_indices_to_samples(self.c)
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_utils.py", line 36, in map_indices_to_samples
    assert sorted(d.keys()) == range(len(d))
AssertionError
```

**Comment by brentp** [comment]
What does `gemini  --version` show?
This is working for me. See below:

```
brentp@x1:~/src/vcf2db$ cat my.ped
fam1    20  0   0   -9  -9
brentp@x1:~/src/vcf2db$ rm my.db
brentp@x1:~/src/vcf2db$ python vcf2db.py ~/Downloads/sample_new.snpeff.gvcf.anno.gz my.ped my.db
/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'fam1'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '-9'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
10000 variant_impacts:1019  effects time: 0.7   chunk time:2.5  4048.36 variants/second
20000 variant_impacts:139   effects time: 0.6   chunk time:2.3  4216.56 variants/second
30000 variant_impacts:457   effects time: 0.6   chunk time:2.2  4341.59 variants/second
33336 variant_impacts:169   effects time: 0.2   chunk time:0.7  4363.94 variants/second
indexing ... finished in 0.1 seconds...
total time: in 7.8 seconds...
brentp@x1:~/src/vcf2db$ gemini query -q "select * from variants" my.db | head | cut -f 1-5
1   chr4    54243810    54243904    None
2   chr4    54243904    None    None
3   chr4    54243905    54244236    None
4   chr4    54244236    54244238    None
5   chr4    54244238    54244241    None
6   chr4    54244241    54244244    None
7   chr4    54244244    54244247    None
8   chr4    54244247    54244251    None
9   chr4    54244251    54244252    None
10  chr4    54244252    54244259    None
```

**Comment by komalsrathi** [comment]
I am using an older version `0.18.3`

**Comment by brentp** [comment]
I don't recall the specific change that would cause this, but updating to 0.19.1 will probably resolve this.

**Comment by komalsrathi** [comment]
Alright thanks - will update everything, test and close this issue if it works. Thanks for your help!
